### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct
trust_remote_code: true

### export
export_dir: saves/qwen2.5-coder-7b/lora/sft
export_hub_model_id: "cudaoom/qwen2.5-coder-7b-lora-sft-ds3"
export_size: 5
export_device: cpu
export_legacy_format: false

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
# dataset: code_update_dataset_0-2048,code_update_dataset_2049-4096,code_update_dataset_4097-8192
# dataset: code_update_dataset_4097-8192
dataset: code_update_dataset_2048
template: qwen
cutoff_len: 8192
max_samples: 200000
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: saves/qwen2.5-coder-7b/lora/sft
overwrite_output_dir: false  # Set to false to enable checkpoint resumption
logging_steps: 10
save_steps: 400
save_total_limit: 2
plot_loss: true

### train
per_device_train_batch_size: 6
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 1
lr_scheduler_type: inverse_sqrt
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 5
eval_strategy: steps
eval_steps: 500 